apiVersion: v1
kind: ConfigMap
metadata:
  name: veera12345-config
  namespace: sample-app-namespace-1750910701034
  labels:
    app.kubernetes.io/name: veera12345
    kubernetes.azure.com/generator: devhub
data: