apiVersion: v1
kind: ConfigMap
metadata:
  name: veera2204-config
  namespace: sample-app-namespace-1751429346891
  labels:
    app.kubernetes.io/name: veera2204
    kubernetes.azure.com/generator: devhub
data: