apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: veera2204
  labels:
    app.kubernetes.io/name: veera2204
    app.kubernetes.io/part-of: veera2204-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: veera2204