apiVersion: v1
kind: Service
metadata:
  name: veerababu1234
  namespace: sample-app-namespace-1750999802323
  labels:
    app.kubernetes.io/name: veerababu1234
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: veerababu1234
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80