apiVersion: v1
kind: Service
metadata:
  name: veera12345
  namespace: sample-app-namespace-1750910701034
  labels:
    app.kubernetes.io/name: veera12345
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: veera12345
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80