apiVersion: v1
kind: Service
metadata:
  name: veera
  namespace: sample-app-namespace-1750772691318
  labels:
    app.kubernetes.io/name: veera
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: veera
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80