apiVersion: v1
kind: Service
metadata:
  name: veera2204
  namespace: sample-app-namespace-1751429346891
  labels:
    app.kubernetes.io/name: veera2204
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: veera2204
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80