apiVersion: v1
kind: Service
metadata:
  name: babu12345
  namespace: sample-app-namespace-1751257296798
  labels:
    app.kubernetes.io/name: babu12345
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: babu12345
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80