apiVersion: v1
kind: Service
metadata:
  name: veera123
  namespace: sample-app-namespace-1750781602228
  labels:
    app.kubernetes.io/name: veera123
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: veera123
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80